
#pragma once
#define MG_ARCH MG_ARCH_NEWLIB
#define MG_ENABLE_MIP 1
#define MG_ENABLE_TCPIP 1
#define MG_ENABLE_CUSTOM_MILLIS 1
#define MG_ENABLE_TCPIP_PRINT_DEBUG_STATS 1
#define MG_ENABLE_POSIX_FS 0
#define MG_ENABLE_DRIVER_W5500 1

